var TREE_ITEMS = [
	["<i>Trees of lusol.f</i>", "lusol_f_c.html", 
  ["<i>Descending tree</i>", "lusol_f_c.html", 
	["lu1fac", "lusol_f_c.html#R_lu1fac", 
		["lu1or1", "lusol_f_c.html#R_lu1or1", 
		],
		["lu1or2", "lusol_f_c.html#R_lu1or2", 
		],
		["lu1or3", "lusol_f_c.html#R_lu1or3", 
		],
		["lu1or4", "lusol_f_c.html#R_lu1or4", 
		],
		["lu1pq1", "lusol_f_c.html#R_lu1pq1", 
		],
		["lu1fad", "lusol_f_c.html#R_lu1fad", 
			["Hbuild", "lusol_f_c.html#R_Hbuild", ],
			["Hchange", "lusol_f_c.html#R_Hchange", ],
			["Hdelete", "lusol_f_c.html#R_Hdelete", ],
			["lu1ful", "lusol_f_c.html#R_lu1ful", ],
			["lu1gau", "lusol_f_c.html#R_lu1gau", ],
			["lu1mar", "lusol_f_c.html#R_lu1mar", ],
			["lu1mRP", "lusol_f_c.html#R_lu1mRP", ],
			["lu1mSP", "lusol_f_c.html#R_lu1mSP", ],
			["lu1mxc", "lusol_f_c.html#R_lu1mxc", ],
			["lu1mxr", "lusol_f_c.html#R_lu1mxr", ],
			["lu1pen", "lusol_f_c.html#R_lu1pen", ],
			["lu1pq2", "lusol_f_c.html#R_lu1pq2", ],
			["lu1pq3", "lusol_f_c.html#R_lu1pq3", ],
			["lu1rec", "lusol_f_c.html#R_lu1rec", ],
			["lu1slk", "lusol_f_c.html#R_lu1slk", ],
		],
		["lu6chk", "lusol_f_c.html#R_lu6chk", 
			["<FONT COLOR=RED>indr</FONT>", "lusol_f_c.html#C_5103", ],
			["<FONT COLOR=RED>ip</FONT>", "lusol_f_c.html#C_5098", ],
			["<FONT COLOR=RED>iq</FONT>", "lusol_f_c.html#C_5117", ],
			["<FONT COLOR=RED>locr</FONT>", "lusol_f_c.html#C_5099", ],
			["<FONT COLOR=RED>luparm</FONT>", "lusol_f_c.html#C_5063", ],
			["<FONT COLOR=RED>parmlu</FONT>", "lusol_f_c.html#C_5069", ],
			["<FONT COLOR=RED>w</FONT>", "lusol_f_c.html#C_5185", ],
		],
	],
	["lu1fad", "lusol_f_c.html#R_lu1fad", 
		["lu1mxc", "lusol_f_c.html#R_lu1mxc", 
		],
		["lu1slk", "lusol_f_c.html#R_lu1slk", 
		],
		["lu1mxr", "lusol_f_c.html#R_lu1mxr", 
			["<FONT COLOR=RED>indr</FONT>", "lusol_f_c.html#C_3053", ],
			["<FONT COLOR=RED>locc</FONT>", "lusol_f_c.html#C_3057", ],
			["<FONT COLOR=RED>locr</FONT>", "lusol_f_c.html#C_3049", ],
		],
		["Hbuild", "lusol_f_c.html#R_Hbuild", 
			["<FONT COLOR=RED>Ha</FONT>", "lusol_f_c.html#C_4223", ],
			["Hinsert", "lusol_f_c.html#R_Hinsert", ],
			["<FONT COLOR=RED>Hj</FONT>", "lusol_f_c.html#C_4224", ],
			["<FONT COLOR=RED>to</FONT>", "lusol_f_c.html#C_4208", ],
		],
		["lu1mar", "lusol_f_c.html#R_lu1mar", 
			["<FONT COLOR=RED>iploc</FONT>", "lusol_f_c.html#C_2254", ],
			["<FONT COLOR=RED>iqloc</FONT>", "lusol_f_c.html#C_2146", ],
			["<FONT COLOR=RED>lenc</FONT>", "lusol_f_c.html#C_2266", ],
			["<FONT COLOR=RED>lenr</FONT>", "lusol_f_c.html#C_2167", ],
		],
		["lu1mRP", "lusol_f_c.html#R_lu1mRP", 
			["<FONT COLOR=RED>Amaxr</FONT>", "lusol_f_c.html#C_2512", ],
			["<FONT COLOR=RED>indc</FONT>", "lusol_f_c.html#C_2447", ],
			["<FONT COLOR=RED>indr</FONT>", "lusol_f_c.html#C_2515", ],
			["<FONT COLOR=RED>ip</FONT>", "lusol_f_c.html#C_2509", ],
			["<FONT COLOR=RED>iploc</FONT>", "lusol_f_c.html#C_2503", ],
			["<FONT COLOR=RED>iq</FONT>", "lusol_f_c.html#C_2438", ],
			["<FONT COLOR=RED>iqloc</FONT>", "lusol_f_c.html#C_2432", ],
			["<FONT COLOR=RED>lenc</FONT>", "lusol_f_c.html#C_2516", ],
			["<FONT COLOR=RED>lenr</FONT>", "lusol_f_c.html#C_2448", ],
			["<FONT COLOR=RED>locc</FONT>", "lusol_f_c.html#C_2439", ],
			["<FONT COLOR=RED>locr</FONT>", "lusol_f_c.html#C_2510", ],
		],
		["lu1mSP", "lusol_f_c.html#R_lu1mSP", 
			["<FONT COLOR=RED>indc</FONT>", "lusol_f_c.html#C_2806", ],
			["<FONT COLOR=RED>iq</FONT>", "lusol_f_c.html#C_2796", ],
			["<FONT COLOR=RED>iqloc</FONT>", "lusol_f_c.html#C_2790", ],
			["<FONT COLOR=RED>locc</FONT>", "lusol_f_c.html#C_2797", ],
		],
		["lu1rec", "lusol_f_c.html#R_lu1rec", 
		],
		["Hdelete", "lusol_f_c.html#R_Hdelete", 
			["<FONT COLOR=RED>Ha</FONT>", "lusol_f_c.html#C_4299", ],
			["Hchange", "lusol_f_c.html#R_Hchange", ],
			["<FONT COLOR=RED>Hj</FONT>", "lusol_f_c.html#C_4300", ],
		],
		["lu1gau", "lusol_f_c.html#R_lu1gau", 
		],
		["lu1pen", "lusol_f_c.html#R_lu1pen", 
		],
		["lu1pq2", "lusol_f_c.html#R_lu1pq2", 
			["<FONT COLOR=RED>iq</FONT>", "lusol_f_c.html#C_3440", ],
			["<FONT COLOR=RED>iqinv</FONT>", "lusol_f_c.html#C_3428", ],
			["<FONT COLOR=RED>iqloc</FONT>", "lusol_f_c.html#C_3438", ],
		],
		["Hchange", "lusol_f_c.html#R_Hchange", 
			["<FONT COLOR=RED>Ha</FONT>", "lusol_f_c.html#C_4258", ],
			["Hdown", "lusol_f_c.html#R_Hdown", ],
			["Hup", "lusol_f_c.html#R_Hup", ],
		],
		["lu1pq3", "lusol_f_c.html#R_lu1pq3", 
		],
		["lu1ful", "lusol_f_c.html#R_lu1ful", 
			["dcopy", "lusol_f_c.html#R_dcopy", ],
			["lu1DCP", "lusol_f_c.html#R_lu1DCP", ],
			["lu1DPP", "lusol_f_c.html#R_lu1DPP", ],
		],
	],
	["lu1gau", "lusol_f_c.html#R_lu1gau", 
	],
	["lu1mar", "lusol_f_c.html#R_lu1mar", 
		["<FONT COLOR=RED>iqloc</FONT>", "lusol_f_c.html#C_2146", ],
		["<FONT COLOR=RED>lenr</FONT>", "lusol_f_c.html#C_2167", ],
		["<FONT COLOR=RED>iploc</FONT>", "lusol_f_c.html#C_2254", ],
		["<FONT COLOR=RED>lenc</FONT>", "lusol_f_c.html#C_2266", ],
	],
	["lu1mRP", "lusol_f_c.html#R_lu1mRP", 
		["<FONT COLOR=RED>iqloc</FONT>", "lusol_f_c.html#C_2432", ],
		["<FONT COLOR=RED>iq</FONT>", "lusol_f_c.html#C_2438", ],
		["<FONT COLOR=RED>locc</FONT>", "lusol_f_c.html#C_2439", ],
		["<FONT COLOR=RED>indc</FONT>", "lusol_f_c.html#C_2447", ],
		["<FONT COLOR=RED>lenr</FONT>", "lusol_f_c.html#C_2448", ],
		["<FONT COLOR=RED>iploc</FONT>", "lusol_f_c.html#C_2503", ],
		["<FONT COLOR=RED>ip</FONT>", "lusol_f_c.html#C_2509", ],
		["<FONT COLOR=RED>locr</FONT>", "lusol_f_c.html#C_2510", ],
		["<FONT COLOR=RED>Amaxr</FONT>", "lusol_f_c.html#C_2512", ],
		["<FONT COLOR=RED>indr</FONT>", "lusol_f_c.html#C_2515", ],
		["<FONT COLOR=RED>lenc</FONT>", "lusol_f_c.html#C_2516", ],
	],
	["lu1mCP", "lusol_f_c.html#R_lu1mCP", 
		["<FONT COLOR=RED>Hj</FONT>", "lusol_f_c.html#C_2629", ],
		["<FONT COLOR=RED>lenc</FONT>", "lusol_f_c.html#C_2630", ],
		["<FONT COLOR=RED>locc</FONT>", "lusol_f_c.html#C_2649", ],
		["<FONT COLOR=RED>lenr</FONT>", "lusol_f_c.html#C_2659", ],
	],
	["lu1mSP", "lusol_f_c.html#R_lu1mSP", 
		["<FONT COLOR=RED>iqloc</FONT>", "lusol_f_c.html#C_2790", ],
		["<FONT COLOR=RED>iq</FONT>", "lusol_f_c.html#C_2796", ],
		["<FONT COLOR=RED>locc</FONT>", "lusol_f_c.html#C_2797", ],
		["<FONT COLOR=RED>indc</FONT>", "lusol_f_c.html#C_2806", ],
	],
	["lu1pen", "lusol_f_c.html#R_lu1pen", 
	],
	["lu1mxc", "lusol_f_c.html#R_lu1mxc", 
	],
	["lu1mxr", "lusol_f_c.html#R_lu1mxr", 
		["<FONT COLOR=RED>locr</FONT>", "lusol_f_c.html#C_3049", ],
		["<FONT COLOR=RED>indr</FONT>", "lusol_f_c.html#C_3053", ],
		["<FONT COLOR=RED>locc</FONT>", "lusol_f_c.html#C_3057", ],
	],
	["lu1or1", "lusol_f_c.html#R_lu1or1", 
	],
	["lu1or2", "lusol_f_c.html#R_lu1or2", 
	],
	["lu1or3", "lusol_f_c.html#R_lu1or3", 
	],
	["lu1or4", "lusol_f_c.html#R_lu1or4", 
	],
	["lu1pq1", "lusol_f_c.html#R_lu1pq1", 
	],
	["lu1pq2", "lusol_f_c.html#R_lu1pq2", 
		["<FONT COLOR=RED>iqinv</FONT>", "lusol_f_c.html#C_3428", ],
		["<FONT COLOR=RED>iqloc</FONT>", "lusol_f_c.html#C_3438", ],
		["<FONT COLOR=RED>iq</FONT>", "lusol_f_c.html#C_3440", ],
	],
	["lu1pq3", "lusol_f_c.html#R_lu1pq3", 
	],
	["lu1rec", "lusol_f_c.html#R_lu1rec", 
	],
	["lu1slk", "lusol_f_c.html#R_lu1slk", 
	],
	["lu1ful", "lusol_f_c.html#R_lu1ful", 
		["lu1DPP", "lusol_f_c.html#R_lu1DPP", 
			["daxpy", "lusol_f_c.html#R_daxpy", ],
			["dscal", "lusol_f_c.html#R_dscal", ],
		],
		["lu1DCP", "lusol_f_c.html#R_lu1DCP", 
			["daxpy", "lusol_f_c.html#R_daxpy", ],
			["dscal", "lusol_f_c.html#R_dscal", ],
		],
		["dcopy", "lusol_f_c.html#R_dcopy", 
		],
	],
	["lu1DPP", "lusol_f_c.html#R_lu1DPP", 
		["dscal", "lusol_f_c.html#R_dscal", 
		],
		["daxpy", "lusol_f_c.html#R_daxpy", 
		],
	],
	["lu1DCP", "lusol_f_c.html#R_lu1DCP", 
		["dscal", "lusol_f_c.html#R_dscal", 
		],
		["daxpy", "lusol_f_c.html#R_daxpy", 
		],
	],
	["Hbuild", "lusol_f_c.html#R_Hbuild", 
		["<FONT COLOR=RED>to</FONT>", "lusol_f_c.html#C_4208", ],
		["<FONT COLOR=RED>Ha</FONT>", "lusol_f_c.html#C_4223", ],
		["<FONT COLOR=RED>Hj</FONT>", "lusol_f_c.html#C_4224", ],
		["Hinsert", "lusol_f_c.html#R_Hinsert", 
			["Hup", "lusol_f_c.html#R_Hup", ],
		],
	],
	["Hchange", "lusol_f_c.html#R_Hchange", 
		["<FONT COLOR=RED>Ha</FONT>", "lusol_f_c.html#C_4258", ],
		["Hup", "lusol_f_c.html#R_Hup", 
			["<FONT COLOR=RED>Ha</FONT>", "lusol_f_c.html#C_4422", ],
			["<FONT COLOR=RED>Hj</FONT>", "lusol_f_c.html#C_4423", ],
		],
		["Hdown", "lusol_f_c.html#R_Hdown", 
			["<FONT COLOR=RED>Ha</FONT>", "lusol_f_c.html#C_4335", ],
			["<FONT COLOR=RED>Hj</FONT>", "lusol_f_c.html#C_4336", ],
		],
	],
	["Hdelete", "lusol_f_c.html#R_Hdelete", 
		["<FONT COLOR=RED>Ha</FONT>", "lusol_f_c.html#C_4299", ],
		["<FONT COLOR=RED>Hj</FONT>", "lusol_f_c.html#C_4300", ],
		["Hchange", "lusol_f_c.html#R_Hchange", 
			["<FONT COLOR=RED>Ha</FONT>", "lusol_f_c.html#C_4258", ],
			["Hdown", "lusol_f_c.html#R_Hdown", ],
			["Hup", "lusol_f_c.html#R_Hup", ],
		],
	],
	["Hdown", "lusol_f_c.html#R_Hdown", 
		["<FONT COLOR=RED>Ha</FONT>", "lusol_f_c.html#C_4335", ],
		["<FONT COLOR=RED>Hj</FONT>", "lusol_f_c.html#C_4336", ],
	],
	["Hinsert", "lusol_f_c.html#R_Hinsert", 
		["Hup", "lusol_f_c.html#R_Hup", 
			["<FONT COLOR=RED>Ha</FONT>", "lusol_f_c.html#C_4422", ],
			["<FONT COLOR=RED>Hj</FONT>", "lusol_f_c.html#C_4423", ],
		],
	],
	["Hup", "lusol_f_c.html#R_Hup", 
		["<FONT COLOR=RED>Ha</FONT>", "lusol_f_c.html#C_4422", ],
		["<FONT COLOR=RED>Hj</FONT>", "lusol_f_c.html#C_4423", ],
	],
	["lu6sol", "lusol_f_c.html#R_lu6sol", 
		["lu6L", "lusol_f_c.html#R_lu6L", 
			["<FONT COLOR=RED>indc</FONT>", "lusol_f_c.html#C_4628", ],
			["<FONT COLOR=RED>indr</FONT>", "lusol_f_c.html#C_4621", ],
			["<FONT COLOR=RED>lenc</FONT>", "lusol_f_c.html#C_4618", ],
			["<FONT COLOR=RED>luparm</FONT>", "lusol_f_c.html#C_4610", ],
			["<FONT COLOR=RED>parmlu</FONT>", "lusol_f_c.html#C_4613", ],
			["<FONT COLOR=RED>v</FONT>", "lusol_f_c.html#C_4622", ],
		],
		["lu6Lt", "lusol_f_c.html#R_lu6Lt", 
			["<FONT COLOR=RED>indc</FONT>", "lusol_f_c.html#C_4696", ],
			["<FONT COLOR=RED>indr</FONT>", "lusol_f_c.html#C_4698", ],
			["<FONT COLOR=RED>lenc</FONT>", "lusol_f_c.html#C_4704", ],
			["<FONT COLOR=RED>luparm</FONT>", "lusol_f_c.html#C_4686", ],
			["<FONT COLOR=RED>parmlu</FONT>", "lusol_f_c.html#C_4689", ],
		],
		["lu6U", "lusol_f_c.html#R_lu6U", 
			["<FONT COLOR=RED>indr</FONT>", "lusol_f_c.html#C_4786", ],
			["<FONT COLOR=RED>ip</FONT>", "lusol_f_c.html#C_4766", ],
			["<FONT COLOR=RED>iq</FONT>", "lusol_f_c.html#C_4771", ],
			["<FONT COLOR=RED>locr</FONT>", "lusol_f_c.html#C_4780", ],
			["<FONT COLOR=RED>luparm</FONT>", "lusol_f_c.html#C_4757", ],
			["<FONT COLOR=RED>parmlu</FONT>", "lusol_f_c.html#C_4758", ],
			["<FONT COLOR=RED>v</FONT>", "lusol_f_c.html#C_4779", ],
		],
		["lu6Ut", "lusol_f_c.html#R_lu6Ut", 
			["<FONT COLOR=RED>indr</FONT>", "lusol_f_c.html#C_4876", ],
			["<FONT COLOR=RED>ip</FONT>", "lusol_f_c.html#C_4852", ],
			["<FONT COLOR=RED>iq</FONT>", "lusol_f_c.html#C_4861", ],
			["<FONT COLOR=RED>locr</FONT>", "lusol_f_c.html#C_4868", ],
			["<FONT COLOR=RED>luparm</FONT>", "lusol_f_c.html#C_4845", ],
			["<FONT COLOR=RED>parmlu</FONT>", "lusol_f_c.html#C_4846", ],
			["<FONT COLOR=RED>w</FONT>", "lusol_f_c.html#C_4862", ],
		],
		["lu6LD", "lusol_f_c.html#R_lu6LD", 
			["<FONT COLOR=RED>A</FONT>", "lusol_f_c.html#C_4961", ],
			["<FONT COLOR=RED>indc</FONT>", "lusol_f_c.html#C_4954", ],
			["<FONT COLOR=RED>indr</FONT>", "lusol_f_c.html#C_4947", ],
			["<FONT COLOR=RED>lenc</FONT>", "lusol_f_c.html#C_4944", ],
			["<FONT COLOR=RED>locr</FONT>", "lusol_f_c.html#C_4960", ],
			["<FONT COLOR=RED>luparm</FONT>", "lusol_f_c.html#C_4938", ],
			["<FONT COLOR=RED>parmlu</FONT>", "lusol_f_c.html#C_4939", ],
			["<FONT COLOR=RED>v</FONT>", "lusol_f_c.html#C_4948", ],
		],
	],
	["lu6L", "lusol_f_c.html#R_lu6L", 
		["<FONT COLOR=RED>luparm</FONT>", "lusol_f_c.html#C_4610", ],
		["<FONT COLOR=RED>parmlu</FONT>", "lusol_f_c.html#C_4613", ],
		["<FONT COLOR=RED>lenc</FONT>", "lusol_f_c.html#C_4618", ],
		["<FONT COLOR=RED>indr</FONT>", "lusol_f_c.html#C_4621", ],
		["<FONT COLOR=RED>v</FONT>", "lusol_f_c.html#C_4622", ],
		["<FONT COLOR=RED>indc</FONT>", "lusol_f_c.html#C_4628", ],
	],
	["lu6Lt", "lusol_f_c.html#R_lu6Lt", 
		["<FONT COLOR=RED>luparm</FONT>", "lusol_f_c.html#C_4686", ],
		["<FONT COLOR=RED>parmlu</FONT>", "lusol_f_c.html#C_4689", ],
		["<FONT COLOR=RED>indc</FONT>", "lusol_f_c.html#C_4696", ],
		["<FONT COLOR=RED>indr</FONT>", "lusol_f_c.html#C_4698", ],
		["<FONT COLOR=RED>lenc</FONT>", "lusol_f_c.html#C_4704", ],
	],
	["lu6U", "lusol_f_c.html#R_lu6U", 
		["<FONT COLOR=RED>luparm</FONT>", "lusol_f_c.html#C_4757", ],
		["<FONT COLOR=RED>parmlu</FONT>", "lusol_f_c.html#C_4758", ],
		["<FONT COLOR=RED>ip</FONT>", "lusol_f_c.html#C_4766", ],
		["<FONT COLOR=RED>iq</FONT>", "lusol_f_c.html#C_4771", ],
		["<FONT COLOR=RED>v</FONT>", "lusol_f_c.html#C_4779", ],
		["<FONT COLOR=RED>locr</FONT>", "lusol_f_c.html#C_4780", ],
		["<FONT COLOR=RED>indr</FONT>", "lusol_f_c.html#C_4786", ],
	],
	["lu6Ut", "lusol_f_c.html#R_lu6Ut", 
		["<FONT COLOR=RED>luparm</FONT>", "lusol_f_c.html#C_4845", ],
		["<FONT COLOR=RED>parmlu</FONT>", "lusol_f_c.html#C_4846", ],
		["<FONT COLOR=RED>ip</FONT>", "lusol_f_c.html#C_4852", ],
		["<FONT COLOR=RED>iq</FONT>", "lusol_f_c.html#C_4861", ],
		["<FONT COLOR=RED>w</FONT>", "lusol_f_c.html#C_4862", ],
		["<FONT COLOR=RED>locr</FONT>", "lusol_f_c.html#C_4868", ],
		["<FONT COLOR=RED>indr</FONT>", "lusol_f_c.html#C_4876", ],
	],
	["lu6LD", "lusol_f_c.html#R_lu6LD", 
		["<FONT COLOR=RED>luparm</FONT>", "lusol_f_c.html#C_4938", ],
		["<FONT COLOR=RED>parmlu</FONT>", "lusol_f_c.html#C_4939", ],
		["<FONT COLOR=RED>lenc</FONT>", "lusol_f_c.html#C_4944", ],
		["<FONT COLOR=RED>indr</FONT>", "lusol_f_c.html#C_4947", ],
		["<FONT COLOR=RED>v</FONT>", "lusol_f_c.html#C_4948", ],
		["<FONT COLOR=RED>indc</FONT>", "lusol_f_c.html#C_4954", ],
		["<FONT COLOR=RED>locr</FONT>", "lusol_f_c.html#C_4960", ],
		["<FONT COLOR=RED>A</FONT>", "lusol_f_c.html#C_4961", ],
	],
	["lu6chk", "lusol_f_c.html#R_lu6chk", 
		["<FONT COLOR=RED>luparm</FONT>", "lusol_f_c.html#C_5063", ],
		["<FONT COLOR=RED>parmlu</FONT>", "lusol_f_c.html#C_5069", ],
		["<FONT COLOR=RED>ip</FONT>", "lusol_f_c.html#C_5098", ],
		["<FONT COLOR=RED>locr</FONT>", "lusol_f_c.html#C_5099", ],
		["<FONT COLOR=RED>indr</FONT>", "lusol_f_c.html#C_5103", ],
		["<FONT COLOR=RED>iq</FONT>", "lusol_f_c.html#C_5117", ],
		["<FONT COLOR=RED>w</FONT>", "lusol_f_c.html#C_5185", ],
	],
	["lu6mul", "lusol_f_c.html#R_lu6mul", 
	],
	["lu6prt", "lusol_f_c.html#R_lu6prt", 
		["lu6mul", "lusol_f_c.html#R_lu6mul", 
		],
	],
	["lu6set", "lusol_f_c.html#R_lu6set", 
	],
	["lu7add", "lusol_f_c.html#R_lu7add", 
		["lu1rec", "lusol_f_c.html#R_lu1rec", 
		],
	],
	["lu7cyc", "lusol_f_c.html#R_lu7cyc", 
	],
	["lu7elm", "lusol_f_c.html#R_lu7elm", 
		["lu1rec", "lusol_f_c.html#R_lu1rec", 
		],
	],
	["lu7for", "lusol_f_c.html#R_lu7for", 
		["lu1rec", "lusol_f_c.html#R_lu1rec", 
		],
	],
	["lu7rnk", "lusol_f_c.html#R_lu7rnk", 
	],
	["lu7zap", "lusol_f_c.html#R_lu7zap", 
	],
	["lu7asv", "lusol_f_c.html#R_lu7asv", 
	],
	["lu7bak", "lusol_f_c.html#R_lu7bak", 
		["lu1rec", "lusol_f_c.html#R_lu1rec", 
		],
		["lu7asv", "lusol_f_c.html#R_lu7asv", 
		],
	],
	["lu8rpc", "lusol_f_c.html#R_lu8rpc", 
		["lu7zap", "lusol_f_c.html#R_lu7zap", 
		],
		["lu6sol", "lusol_f_c.html#R_lu6sol", 
			["lu6L", "lusol_f_c.html#R_lu6L", ],
			["lu6LD", "lusol_f_c.html#R_lu6LD", ],
			["lu6Lt", "lusol_f_c.html#R_lu6Lt", ],
			["lu6U", "lusol_f_c.html#R_lu6U", ],
			["lu6Ut", "lusol_f_c.html#R_lu6Ut", ],
		],
		["lu7add", "lusol_f_c.html#R_lu7add", 
			["lu1rec", "lusol_f_c.html#R_lu1rec", ],
		],
		["lu7elm", "lusol_f_c.html#R_lu7elm", 
			["lu1rec", "lusol_f_c.html#R_lu1rec", ],
		],
		["lu7cyc", "lusol_f_c.html#R_lu7cyc", 
		],
		["lu7for", "lusol_f_c.html#R_lu7for", 
			["lu1rec", "lusol_f_c.html#R_lu1rec", ],
		],
		["lu7rnk", "lusol_f_c.html#R_lu7rnk", 
		],
	],
	["lu8adc", "lusol_f_c.html#R_lu8adc", 
		["lu8rpc", "lusol_f_c.html#R_lu8rpc", 
			["lu6sol", "lusol_f_c.html#R_lu6sol", ],
			["lu7add", "lusol_f_c.html#R_lu7add", ],
			["lu7cyc", "lusol_f_c.html#R_lu7cyc", ],
			["lu7elm", "lusol_f_c.html#R_lu7elm", ],
			["lu7for", "lusol_f_c.html#R_lu7for", ],
			["lu7rnk", "lusol_f_c.html#R_lu7rnk", ],
			["lu7zap", "lusol_f_c.html#R_lu7zap", ],
		],
	],
	["lu8adr", "lusol_f_c.html#R_lu8adr", 
		["lu1rec", "lusol_f_c.html#R_lu1rec", 
		],
		["lu7for", "lusol_f_c.html#R_lu7for", 
			["lu1rec", "lusol_f_c.html#R_lu1rec", ],
		],
		["lu7rnk", "lusol_f_c.html#R_lu7rnk", 
		],
	],
	["lu8dlc", "lusol_f_c.html#R_lu8dlc", 
		["lu7zap", "lusol_f_c.html#R_lu7zap", 
		],
		["lu7cyc", "lusol_f_c.html#R_lu7cyc", 
		],
		["lu7for", "lusol_f_c.html#R_lu7for", 
			["lu1rec", "lusol_f_c.html#R_lu1rec", ],
		],
		["lu7rnk", "lusol_f_c.html#R_lu7rnk", 
		],
	],
	["lu8dlr", "lusol_f_c.html#R_lu8dlr", 
		["lu6mul", "lusol_f_c.html#R_lu6mul", 
		],
		["lu8mod", "lusol_f_c.html#R_lu8mod", 
			["lu1rec", "lusol_f_c.html#R_lu1rec", ],
			["lu6sol", "lusol_f_c.html#R_lu6sol", ],
			["lu7asv", "lusol_f_c.html#R_lu7asv", ],
			["lu7bak", "lusol_f_c.html#R_lu7bak", ],
			["lu7cyc", "lusol_f_c.html#R_lu7cyc", ],
			["lu7elm", "lusol_f_c.html#R_lu7elm", ],
			["lu7for", "lusol_f_c.html#R_lu7for", ],
			["lu7rnk", "lusol_f_c.html#R_lu7rnk", ],
		],
		["lu7cyc", "lusol_f_c.html#R_lu7cyc", 
		],
	],
	["lu8mod", "lusol_f_c.html#R_lu8mod", 
		["lu6sol", "lusol_f_c.html#R_lu6sol", 
			["lu6L", "lusol_f_c.html#R_lu6L", ],
			["lu6LD", "lusol_f_c.html#R_lu6LD", ],
			["lu6Lt", "lusol_f_c.html#R_lu6Lt", ],
			["lu6U", "lusol_f_c.html#R_lu6U", ],
			["lu6Ut", "lusol_f_c.html#R_lu6Ut", ],
		],
		["lu7elm", "lusol_f_c.html#R_lu7elm", 
			["lu1rec", "lusol_f_c.html#R_lu1rec", ],
		],
		["lu7bak", "lusol_f_c.html#R_lu7bak", 
			["lu1rec", "lusol_f_c.html#R_lu1rec", ],
			["lu7asv", "lusol_f_c.html#R_lu7asv", ],
		],
		["lu1rec", "lusol_f_c.html#R_lu1rec", 
		],
		["lu7asv", "lusol_f_c.html#R_lu7asv", 
		],
		["lu7for", "lusol_f_c.html#R_lu7for", 
			["lu1rec", "lusol_f_c.html#R_lu1rec", ],
		],
		["lu7cyc", "lusol_f_c.html#R_lu7cyc", 
		],
		["lu7rnk", "lusol_f_c.html#R_lu7rnk", 
		],
	],
	["lu8rpr", "lusol_f_c.html#R_lu8rpr", 
		["lu6mul", "lusol_f_c.html#R_lu6mul", 
		],
		["lu8mod", "lusol_f_c.html#R_lu8mod", 
			["lu1rec", "lusol_f_c.html#R_lu1rec", ],
			["lu6sol", "lusol_f_c.html#R_lu6sol", ],
			["lu7asv", "lusol_f_c.html#R_lu7asv", ],
			["lu7bak", "lusol_f_c.html#R_lu7bak", ],
			["lu7cyc", "lusol_f_c.html#R_lu7cyc", ],
			["lu7elm", "lusol_f_c.html#R_lu7elm", ],
			["lu7for", "lusol_f_c.html#R_lu7for", ],
			["lu7rnk", "lusol_f_c.html#R_lu7rnk", ],
		],
	],
	["dasum", "lusol_f_c.html#R_dasum", 
	],
	["daxpy", "lusol_f_c.html#R_daxpy", 
	],
	["dcopy", "lusol_f_c.html#R_dcopy", 
	],
	["ddot", "lusol_f_c.html#R_ddot", 
	],
	["dscal", "lusol_f_c.html#R_dscal", 
	],
	["idamax", "lusol_f_c.html#R_idamax", 
	],
  ],
  ["<i>Ascending tree</i>", "lusol_f_c.html", 
	["lu1fac", "lusol_f_c.html#R_lu1fac", 
	],
	["lu1fad", "lusol_f_c.html#R_lu1fad", 
		["lu1fac", "lusol_f_c.html#R_lu1fac", 
		],
	],
	["lu1gau", "lusol_f_c.html#R_lu1gau", 
		["lu1fad", "lusol_f_c.html#R_lu1fad", 
			["lu1fac", "lusol_f_c.html#R_lu1fac", ],
		],
	],
	["lu1mar", "lusol_f_c.html#R_lu1mar", 
		["lu1fad", "lusol_f_c.html#R_lu1fad", 
			["lu1fac", "lusol_f_c.html#R_lu1fac", ],
		],
	],
	["lu1mRP", "lusol_f_c.html#R_lu1mRP", 
		["lu1fad", "lusol_f_c.html#R_lu1fad", 
			["lu1fac", "lusol_f_c.html#R_lu1fac", ],
		],
	],
	["lu1mCP", "lusol_f_c.html#R_lu1mCP", 
	],
	["lu1mSP", "lusol_f_c.html#R_lu1mSP", 
		["lu1fad", "lusol_f_c.html#R_lu1fad", 
			["lu1fac", "lusol_f_c.html#R_lu1fac", ],
		],
	],
	["lu1pen", "lusol_f_c.html#R_lu1pen", 
		["lu1fad", "lusol_f_c.html#R_lu1fad", 
			["lu1fac", "lusol_f_c.html#R_lu1fac", ],
		],
	],
	["lu1mxc", "lusol_f_c.html#R_lu1mxc", 
		["lu1fad", "lusol_f_c.html#R_lu1fad", 
			["lu1fac", "lusol_f_c.html#R_lu1fac", ],
		],
	],
	["lu1mxr", "lusol_f_c.html#R_lu1mxr", 
		["lu1fad", "lusol_f_c.html#R_lu1fad", 
			["lu1fac", "lusol_f_c.html#R_lu1fac", ],
		],
	],
	["lu1or1", "lusol_f_c.html#R_lu1or1", 
		["lu1fac", "lusol_f_c.html#R_lu1fac", 
		],
	],
	["lu1or2", "lusol_f_c.html#R_lu1or2", 
		["lu1fac", "lusol_f_c.html#R_lu1fac", 
		],
	],
	["lu1or3", "lusol_f_c.html#R_lu1or3", 
		["lu1fac", "lusol_f_c.html#R_lu1fac", 
		],
	],
	["lu1or4", "lusol_f_c.html#R_lu1or4", 
		["lu1fac", "lusol_f_c.html#R_lu1fac", 
		],
	],
	["lu1pq1", "lusol_f_c.html#R_lu1pq1", 
		["lu1fac", "lusol_f_c.html#R_lu1fac", 
		],
	],
	["lu1pq2", "lusol_f_c.html#R_lu1pq2", 
		["lu1fad", "lusol_f_c.html#R_lu1fad", 
			["lu1fac", "lusol_f_c.html#R_lu1fac", ],
		],
	],
	["lu1pq3", "lusol_f_c.html#R_lu1pq3", 
		["lu1fad", "lusol_f_c.html#R_lu1fad", 
			["lu1fac", "lusol_f_c.html#R_lu1fac", ],
		],
	],
	["lu1rec", "lusol_f_c.html#R_lu1rec", 
		["lu1fad", "lusol_f_c.html#R_lu1fad", 
			["lu1fac", "lusol_f_c.html#R_lu1fac", ],
		],
		["lu7add", "lusol_f_c.html#R_lu7add", 
			["lu8rpc", "lusol_f_c.html#R_lu8rpc", ],
		],
		["lu7bak", "lusol_f_c.html#R_lu7bak", 
			["lu8mod", "lusol_f_c.html#R_lu8mod", ],
		],
		["lu7elm", "lusol_f_c.html#R_lu7elm", 
			["lu8mod", "lusol_f_c.html#R_lu8mod", ],
			["lu8rpc", "lusol_f_c.html#R_lu8rpc", ],
		],
		["lu7for", "lusol_f_c.html#R_lu7for", 
			["lu8adr", "lusol_f_c.html#R_lu8adr", ],
			["lu8dlc", "lusol_f_c.html#R_lu8dlc", ],
			["lu8mod", "lusol_f_c.html#R_lu8mod", ],
			["lu8rpc", "lusol_f_c.html#R_lu8rpc", ],
		],
		["lu8adr", "lusol_f_c.html#R_lu8adr", 
		],
		["lu8mod", "lusol_f_c.html#R_lu8mod", 
			["lu8dlr", "lusol_f_c.html#R_lu8dlr", ],
			["lu8rpr", "lusol_f_c.html#R_lu8rpr", ],
		],
	],
	["lu1slk", "lusol_f_c.html#R_lu1slk", 
		["lu1fad", "lusol_f_c.html#R_lu1fad", 
			["lu1fac", "lusol_f_c.html#R_lu1fac", ],
		],
	],
	["lu1ful", "lusol_f_c.html#R_lu1ful", 
		["lu1fad", "lusol_f_c.html#R_lu1fad", 
			["lu1fac", "lusol_f_c.html#R_lu1fac", ],
		],
	],
	["lu1DPP", "lusol_f_c.html#R_lu1DPP", 
		["lu1ful", "lusol_f_c.html#R_lu1ful", 
			["lu1fad", "lusol_f_c.html#R_lu1fad", ],
		],
	],
	["lu1DCP", "lusol_f_c.html#R_lu1DCP", 
		["lu1ful", "lusol_f_c.html#R_lu1ful", 
			["lu1fad", "lusol_f_c.html#R_lu1fad", ],
		],
	],
	["Hbuild", "lusol_f_c.html#R_Hbuild", 
		["lu1fad", "lusol_f_c.html#R_lu1fad", 
			["lu1fac", "lusol_f_c.html#R_lu1fac", ],
		],
	],
	["Hchange", "lusol_f_c.html#R_Hchange", 
		["Hdelete", "lusol_f_c.html#R_Hdelete", 
			["lu1fad", "lusol_f_c.html#R_lu1fad", ],
		],
		["lu1fad", "lusol_f_c.html#R_lu1fad", 
			["lu1fac", "lusol_f_c.html#R_lu1fac", ],
		],
	],
	["Hdelete", "lusol_f_c.html#R_Hdelete", 
		["lu1fad", "lusol_f_c.html#R_lu1fad", 
			["lu1fac", "lusol_f_c.html#R_lu1fac", ],
		],
	],
	["Hdown", "lusol_f_c.html#R_Hdown", 
		["Hchange", "lusol_f_c.html#R_Hchange", 
			["Hdelete", "lusol_f_c.html#R_Hdelete", ],
			["lu1fad", "lusol_f_c.html#R_lu1fad", ],
		],
	],
	["Hinsert", "lusol_f_c.html#R_Hinsert", 
		["Hbuild", "lusol_f_c.html#R_Hbuild", 
			["lu1fad", "lusol_f_c.html#R_lu1fad", ],
		],
	],
	["Hup", "lusol_f_c.html#R_Hup", 
		["Hchange", "lusol_f_c.html#R_Hchange", 
			["Hdelete", "lusol_f_c.html#R_Hdelete", ],
			["lu1fad", "lusol_f_c.html#R_lu1fad", ],
		],
		["Hinsert", "lusol_f_c.html#R_Hinsert", 
			["Hbuild", "lusol_f_c.html#R_Hbuild", ],
		],
	],
	["lu6sol", "lusol_f_c.html#R_lu6sol", 
		["lu8mod", "lusol_f_c.html#R_lu8mod", 
			["lu8dlr", "lusol_f_c.html#R_lu8dlr", ],
			["lu8rpr", "lusol_f_c.html#R_lu8rpr", ],
		],
		["lu8rpc", "lusol_f_c.html#R_lu8rpc", 
			["lu8adc", "lusol_f_c.html#R_lu8adc", ],
		],
	],
	["lu6L", "lusol_f_c.html#R_lu6L", 
		["lu6sol", "lusol_f_c.html#R_lu6sol", 
			["lu8mod", "lusol_f_c.html#R_lu8mod", ],
			["lu8rpc", "lusol_f_c.html#R_lu8rpc", ],
		],
	],
	["lu6Lt", "lusol_f_c.html#R_lu6Lt", 
		["lu6sol", "lusol_f_c.html#R_lu6sol", 
			["lu8mod", "lusol_f_c.html#R_lu8mod", ],
			["lu8rpc", "lusol_f_c.html#R_lu8rpc", ],
		],
	],
	["lu6U", "lusol_f_c.html#R_lu6U", 
		["lu6sol", "lusol_f_c.html#R_lu6sol", 
			["lu8mod", "lusol_f_c.html#R_lu8mod", ],
			["lu8rpc", "lusol_f_c.html#R_lu8rpc", ],
		],
	],
	["lu6Ut", "lusol_f_c.html#R_lu6Ut", 
		["lu6sol", "lusol_f_c.html#R_lu6sol", 
			["lu8mod", "lusol_f_c.html#R_lu8mod", ],
			["lu8rpc", "lusol_f_c.html#R_lu8rpc", ],
		],
	],
	["lu6LD", "lusol_f_c.html#R_lu6LD", 
		["lu6sol", "lusol_f_c.html#R_lu6sol", 
			["lu8mod", "lusol_f_c.html#R_lu8mod", ],
			["lu8rpc", "lusol_f_c.html#R_lu8rpc", ],
		],
	],
	["lu6chk", "lusol_f_c.html#R_lu6chk", 
		["lu1fac", "lusol_f_c.html#R_lu1fac", 
		],
	],
	["lu6mul", "lusol_f_c.html#R_lu6mul", 
		["lu6prt", "lusol_f_c.html#R_lu6prt", 
		],
		["lu8dlr", "lusol_f_c.html#R_lu8dlr", 
		],
		["lu8rpr", "lusol_f_c.html#R_lu8rpr", 
		],
	],
	["lu6prt", "lusol_f_c.html#R_lu6prt", 
	],
	["lu6set", "lusol_f_c.html#R_lu6set", 
	],
	["lu7add", "lusol_f_c.html#R_lu7add", 
		["lu8rpc", "lusol_f_c.html#R_lu8rpc", 
			["lu8adc", "lusol_f_c.html#R_lu8adc", ],
		],
	],
	["lu7cyc", "lusol_f_c.html#R_lu7cyc", 
		["lu8dlc", "lusol_f_c.html#R_lu8dlc", 
		],
		["lu8dlr", "lusol_f_c.html#R_lu8dlr", 
		],
		["lu8mod", "lusol_f_c.html#R_lu8mod", 
			["lu8dlr", "lusol_f_c.html#R_lu8dlr", ],
			["lu8rpr", "lusol_f_c.html#R_lu8rpr", ],
		],
		["lu8rpc", "lusol_f_c.html#R_lu8rpc", 
			["lu8adc", "lusol_f_c.html#R_lu8adc", ],
		],
	],
	["lu7elm", "lusol_f_c.html#R_lu7elm", 
		["lu8mod", "lusol_f_c.html#R_lu8mod", 
			["lu8dlr", "lusol_f_c.html#R_lu8dlr", ],
			["lu8rpr", "lusol_f_c.html#R_lu8rpr", ],
		],
		["lu8rpc", "lusol_f_c.html#R_lu8rpc", 
			["lu8adc", "lusol_f_c.html#R_lu8adc", ],
		],
	],
	["lu7for", "lusol_f_c.html#R_lu7for", 
		["lu8adr", "lusol_f_c.html#R_lu8adr", 
		],
		["lu8dlc", "lusol_f_c.html#R_lu8dlc", 
		],
		["lu8mod", "lusol_f_c.html#R_lu8mod", 
			["lu8dlr", "lusol_f_c.html#R_lu8dlr", ],
			["lu8rpr", "lusol_f_c.html#R_lu8rpr", ],
		],
		["lu8rpc", "lusol_f_c.html#R_lu8rpc", 
			["lu8adc", "lusol_f_c.html#R_lu8adc", ],
		],
	],
	["lu7rnk", "lusol_f_c.html#R_lu7rnk", 
		["lu8adr", "lusol_f_c.html#R_lu8adr", 
		],
		["lu8dlc", "lusol_f_c.html#R_lu8dlc", 
		],
		["lu8mod", "lusol_f_c.html#R_lu8mod", 
			["lu8dlr", "lusol_f_c.html#R_lu8dlr", ],
			["lu8rpr", "lusol_f_c.html#R_lu8rpr", ],
		],
		["lu8rpc", "lusol_f_c.html#R_lu8rpc", 
			["lu8adc", "lusol_f_c.html#R_lu8adc", ],
		],
	],
	["lu7zap", "lusol_f_c.html#R_lu7zap", 
		["lu8dlc", "lusol_f_c.html#R_lu8dlc", 
		],
		["lu8rpc", "lusol_f_c.html#R_lu8rpc", 
			["lu8adc", "lusol_f_c.html#R_lu8adc", ],
		],
	],
	["lu7asv", "lusol_f_c.html#R_lu7asv", 
		["lu7bak", "lusol_f_c.html#R_lu7bak", 
			["lu8mod", "lusol_f_c.html#R_lu8mod", ],
		],
		["lu8mod", "lusol_f_c.html#R_lu8mod", 
			["lu8dlr", "lusol_f_c.html#R_lu8dlr", ],
			["lu8rpr", "lusol_f_c.html#R_lu8rpr", ],
		],
	],
	["lu7bak", "lusol_f_c.html#R_lu7bak", 
		["lu8mod", "lusol_f_c.html#R_lu8mod", 
			["lu8dlr", "lusol_f_c.html#R_lu8dlr", ],
			["lu8rpr", "lusol_f_c.html#R_lu8rpr", ],
		],
	],
	["lu8rpc", "lusol_f_c.html#R_lu8rpc", 
		["lu8adc", "lusol_f_c.html#R_lu8adc", 
		],
	],
	["lu8adc", "lusol_f_c.html#R_lu8adc", 
	],
	["lu8adr", "lusol_f_c.html#R_lu8adr", 
	],
	["lu8dlc", "lusol_f_c.html#R_lu8dlc", 
	],
	["lu8dlr", "lusol_f_c.html#R_lu8dlr", 
	],
	["lu8mod", "lusol_f_c.html#R_lu8mod", 
		["lu8dlr", "lusol_f_c.html#R_lu8dlr", 
		],
		["lu8rpr", "lusol_f_c.html#R_lu8rpr", 
		],
	],
	["lu8rpr", "lusol_f_c.html#R_lu8rpr", 
	],
	["dasum", "lusol_f_c.html#R_dasum", 
	],
	["daxpy", "lusol_f_c.html#R_daxpy", 
		["lu1DCP", "lusol_f_c.html#R_lu1DCP", 
			["lu1ful", "lusol_f_c.html#R_lu1ful", ],
		],
		["lu1DPP", "lusol_f_c.html#R_lu1DPP", 
			["lu1ful", "lusol_f_c.html#R_lu1ful", ],
		],
	],
	["dcopy", "lusol_f_c.html#R_dcopy", 
		["lu1ful", "lusol_f_c.html#R_lu1ful", 
			["lu1fad", "lusol_f_c.html#R_lu1fad", ],
		],
	],
	["ddot", "lusol_f_c.html#R_ddot", 
	],
	["dscal", "lusol_f_c.html#R_dscal", 
		["lu1DCP", "lusol_f_c.html#R_lu1DCP", 
			["lu1ful", "lusol_f_c.html#R_lu1ful", ],
		],
		["lu1DPP", "lusol_f_c.html#R_lu1DPP", 
			["lu1ful", "lusol_f_c.html#R_lu1ful", ],
		],
	],
	["idamax", "lusol_f_c.html#R_idamax", 
	],
  ],
	]
];
